//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.07 at 04:13:44 PM GMT 
//


package ie.gmit.sw.Model;

import java.io.Serializable;
import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OrderID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="OrderNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="car" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="cust" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "orderID",
    "date",
    "custFName",
    "custSName",
    "custID",
    "carReg",
    "dateFrom",
    "dateTo"
})
@XmlRootElement(name = "Order")
public class Order implements Serializable{

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@XmlElement(name = "OrderID")
    protected int orderID;
    @XmlElement(name = "Date", required = true)
    @XmlSchemaType(name = "date")
    protected Date date;
    protected String custFName;
    protected String custSName;
    protected int custID;
    protected String carReg;
    @XmlElement(name = "dateFrom", required = true)
    @XmlSchemaType(name = "dateFrom")
    protected String dateFrom;
    @XmlElement(name = "dateTo", required = true)
    @XmlSchemaType(name = "dateTo")
    protected String dateTo;

    
    public Order() {
		super();
	}
    public Order(int orderID, Date date, String custFName, String custSName, int custID, String carReg, String dateFrom, String dateTo) {
		super();
		this.orderID = orderID;
		this.date = date;
		this.custFName = custFName;
		this.custSName = custSName;
		this.custID = custID;
		this.carReg = carReg;
		this.dateFrom = dateFrom;
		this.dateTo = dateTo;
	}
	public int getOrderID() {
		return orderID;
	}
	public void setOrderID(int orderID) {
		this.orderID = orderID;
	}
	public Date getDate() {
		return date;
	}
	public void setDate(Date date) {
		this.date = date;
	}
	public String getCustFName() {
		return custFName;
	}
	public void setCustFName(String custFName) {
		this.custFName = custFName;
	}
	public String getCustSName() {
		return custSName;
	}
	public void setCustSName(String custSName) {
		this.custSName = custSName;
	}
	public int getCustID() {
		return custID;
	}
	public void setCustID(int custID) {
		this.custID = custID;
	}
	public String getCarReg() {
		return carReg;
	}
	public void setCarReg(String carReg) {
		this.carReg = carReg;
	}
	public String getDateFrom() {
		return dateFrom;
	}
	public void setDateFrom(String dateFrom) {
		this.dateFrom = dateFrom;
	}
	public String getDateTo() {
		return dateTo;
	}
	public void setDateTo(String dateTo) {
		this.dateTo = dateTo;
	}
}
